binop_separator = "Back"
combine_control_expr = false
edition = "2018"
error_on_line_overflow = true
format_code_in_doc_comments = true
format_macro_matchers = true
format_strings = true
match_block_trailing_comma = true
imports_granularity = "Crate"
imports_layout = "Vertical"
newline_style = "Unix"
normalize_comments = true
normalize_doc_attributes = true
overflow_delimited_expr = true
remove_nested_parens = true
use_field_init_shorthand = true
use_try_shorthand = true
version = "Two"
wrap_comments = true
reorder_impl_items = true
group_imports = "StdExternalCrate"
